<<<<<<< HEAD
# Meta data
name:             Bootflat
authors:          flathemes
description:      BOOTFLAT is an open source Flat UI KIT based on Bootstrap 3.3.0 CSS framework. And, for the designers, we offer a free PSD Download. It provides a faster, easier and less repetitive way for web developers or designers to create elegant web apps.

# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           docs
url:              http://bootflat.github.io
encoding:         UTF-8

# Custom vars
current_version:  2.0.4
repo:             https://github.com/bootflat/bootflat.github.io
=======
theme: jekyll-theme-slate
>>>>>>> 99a4b01bc6f4bc93c9966e4c79512811076f5c1e
